//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
[System.Xml.Serialization.XmlRootAttribute("route", Namespace="http://www.cirm.org/RTZ/1/0", IsNullable=false)]
public partial class Route {
    
    private RouteInfo routeInfoField;
    
    private Waypoints waypointsField;
    
    private Schedules schedulesField;
    
    private Extensions extensionsField;
    
    private string versionField;
    
    public Route() {
        this.versionField = "1.0";
    }
    
    /// <remarks/>
    public RouteInfo routeInfo {
        get {
            return this.routeInfoField;
        }
        set {
            this.routeInfoField = value;
        }
    }
    
    /// <remarks/>
    public Waypoints waypoints {
        get {
            return this.waypointsField;
        }
        set {
            this.waypointsField = value;
        }
    }
    
    /// <remarks/>
    public Schedules schedules {
        get {
            return this.schedulesField;
        }
        set {
            this.schedulesField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class RouteInfo {
    
    private Extensions extensionsField;
    
    private string routeNameField;
    
    private string routeAuthorField;
    
    private string routeStatusField;
    
    private System.DateTime validityPeriodStartField;
    
    private bool validityPeriodStartFieldSpecified;
    
    private System.DateTime validityPeriodStopField;
    
    private bool validityPeriodStopFieldSpecified;
    
    private string vesselNameField;
    
    private string vesselMMSIField;
    
    private string vesselIMOField;
    
    private string vesselVoyageField;
    
    private string vesselDisplacementField;
    
    private string vesselCargoField;
    
    private decimal vesselGMField;
    
    private bool vesselGMFieldSpecified;
    
    private string optimizationMethodField;
    
    private string vesselMaxRollField;
    
    private decimal vesselMaxWaveField;
    
    private bool vesselMaxWaveFieldSpecified;
    
    private decimal vesselMaxWindField;
    
    private bool vesselMaxWindFieldSpecified;
    
    private decimal vesselSpeedMaxField;
    
    private bool vesselSpeedMaxFieldSpecified;
    
    private decimal vesselServiceMinField;
    
    private bool vesselServiceMinFieldSpecified;
    
    private decimal vesselServiceMaxField;
    
    private bool vesselServiceMaxFieldSpecified;
    
    private decimal routeChangesHistoryField;
    
    private bool routeChangesHistoryFieldSpecified;
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string routeName {
        get {
            return this.routeNameField;
        }
        set {
            this.routeNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string routeAuthor {
        get {
            return this.routeAuthorField;
        }
        set {
            this.routeAuthorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string routeStatus {
        get {
            return this.routeStatusField;
        }
        set {
            this.routeStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime validityPeriodStart {
        get {
            return this.validityPeriodStartField;
        }
        set {
            this.validityPeriodStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityPeriodStartSpecified {
        get {
            return this.validityPeriodStartFieldSpecified;
        }
        set {
            this.validityPeriodStartFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime validityPeriodStop {
        get {
            return this.validityPeriodStopField;
        }
        set {
            this.validityPeriodStopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityPeriodStopSpecified {
        get {
            return this.validityPeriodStopFieldSpecified;
        }
        set {
            this.validityPeriodStopFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vesselName {
        get {
            return this.vesselNameField;
        }
        set {
            this.vesselNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string vesselMMSI {
        get {
            return this.vesselMMSIField;
        }
        set {
            this.vesselMMSIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string vesselIMO {
        get {
            return this.vesselIMOField;
        }
        set {
            this.vesselIMOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string vesselVoyage {
        get {
            return this.vesselVoyageField;
        }
        set {
            this.vesselVoyageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string vesselDisplacement {
        get {
            return this.vesselDisplacementField;
        }
        set {
            this.vesselDisplacementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string vesselCargo {
        get {
            return this.vesselCargoField;
        }
        set {
            this.vesselCargoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vesselGM {
        get {
            return this.vesselGMField;
        }
        set {
            this.vesselGMField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vesselGMSpecified {
        get {
            return this.vesselGMFieldSpecified;
        }
        set {
            this.vesselGMFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string optimizationMethod {
        get {
            return this.optimizationMethodField;
        }
        set {
            this.optimizationMethodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string vesselMaxRoll {
        get {
            return this.vesselMaxRollField;
        }
        set {
            this.vesselMaxRollField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vesselMaxWave {
        get {
            return this.vesselMaxWaveField;
        }
        set {
            this.vesselMaxWaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vesselMaxWaveSpecified {
        get {
            return this.vesselMaxWaveFieldSpecified;
        }
        set {
            this.vesselMaxWaveFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vesselMaxWind {
        get {
            return this.vesselMaxWindField;
        }
        set {
            this.vesselMaxWindField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vesselMaxWindSpecified {
        get {
            return this.vesselMaxWindFieldSpecified;
        }
        set {
            this.vesselMaxWindFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vesselSpeedMax {
        get {
            return this.vesselSpeedMaxField;
        }
        set {
            this.vesselSpeedMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vesselSpeedMaxSpecified {
        get {
            return this.vesselSpeedMaxFieldSpecified;
        }
        set {
            this.vesselSpeedMaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vesselServiceMin {
        get {
            return this.vesselServiceMinField;
        }
        set {
            this.vesselServiceMinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vesselServiceMinSpecified {
        get {
            return this.vesselServiceMinFieldSpecified;
        }
        set {
            this.vesselServiceMinFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal vesselServiceMax {
        get {
            return this.vesselServiceMaxField;
        }
        set {
            this.vesselServiceMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool vesselServiceMaxSpecified {
        get {
            return this.vesselServiceMaxFieldSpecified;
        }
        set {
            this.vesselServiceMaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal routeChangesHistory {
        get {
            return this.routeChangesHistoryField;
        }
        set {
            this.routeChangesHistoryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool routeChangesHistorySpecified {
        get {
            return this.routeChangesHistoryFieldSpecified;
        }
        set {
            this.routeChangesHistoryFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Extensions {
    
    private System.Xml.XmlElement[] anyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyElementAttribute()]
    public System.Xml.XmlElement[] Any {
        get {
            return this.anyField;
        }
        set {
            this.anyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Calculated {
    
    private ScheduleElement[] sheduleElementField;
    
    private Extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sheduleElement")]
    public ScheduleElement[] sheduleElement {
        get {
            return this.sheduleElementField;
        }
        set {
            this.sheduleElementField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class ScheduleElement {
    
    private Extensions extensionsField;
    
    private string waypointIdField;
    
    private System.DateTime etdField;
    
    private bool etdFieldSpecified;
    
    private System.DateTime etdWindowBeforeField;
    
    private bool etdWindowBeforeFieldSpecified;
    
    private System.DateTime etdWindowAfterField;
    
    private bool etdWindowAfterFieldSpecified;
    
    private System.DateTime etaField;
    
    private bool etaFieldSpecified;
    
    private System.DateTime etaWindowBeforeField;
    
    private bool etaWindowBeforeFieldSpecified;
    
    private System.DateTime etaWindowAfterField;
    
    private bool etaWindowAfterFieldSpecified;
    
    private System.DateTime stayField;
    
    private bool stayFieldSpecified;
    
    private decimal speedField;
    
    private bool speedFieldSpecified;
    
    private decimal speedWindowField;
    
    private bool speedWindowFieldSpecified;
    
    private decimal windSpeedField;
    
    private bool windSpeedFieldSpecified;
    
    private decimal windDirectionField;
    
    private bool windDirectionFieldSpecified;
    
    private decimal currentSpeedField;
    
    private bool currentSpeedFieldSpecified;
    
    private decimal currentDirectionField;
    
    private bool currentDirectionFieldSpecified;
    
    private decimal windLossField;
    
    private bool windLossFieldSpecified;
    
    private decimal waveLossField;
    
    private bool waveLossFieldSpecified;
    
    private decimal totalLossField;
    
    private bool totalLossFieldSpecified;
    
    private string rpmField;
    
    private string pitchField;
    
    private decimal fuelField;
    
    private bool fuelFieldSpecified;
    
    private decimal relFuelSaveField;
    
    private bool relFuelSaveFieldSpecified;
    
    private decimal absFuelSaceField;
    
    private bool absFuelSaceFieldSpecified;
    
    private string noteField;
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string waypointId {
        get {
            return this.waypointIdField;
        }
        set {
            this.waypointIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime etd {
        get {
            return this.etdField;
        }
        set {
            this.etdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool etdSpecified {
        get {
            return this.etdFieldSpecified;
        }
        set {
            this.etdFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime etdWindowBefore {
        get {
            return this.etdWindowBeforeField;
        }
        set {
            this.etdWindowBeforeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool etdWindowBeforeSpecified {
        get {
            return this.etdWindowBeforeFieldSpecified;
        }
        set {
            this.etdWindowBeforeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime etdWindowAfter {
        get {
            return this.etdWindowAfterField;
        }
        set {
            this.etdWindowAfterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool etdWindowAfterSpecified {
        get {
            return this.etdWindowAfterFieldSpecified;
        }
        set {
            this.etdWindowAfterFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime eta {
        get {
            return this.etaField;
        }
        set {
            this.etaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool etaSpecified {
        get {
            return this.etaFieldSpecified;
        }
        set {
            this.etaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime etaWindowBefore {
        get {
            return this.etaWindowBeforeField;
        }
        set {
            this.etaWindowBeforeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool etaWindowBeforeSpecified {
        get {
            return this.etaWindowBeforeFieldSpecified;
        }
        set {
            this.etaWindowBeforeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime etaWindowAfter {
        get {
            return this.etaWindowAfterField;
        }
        set {
            this.etaWindowAfterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool etaWindowAfterSpecified {
        get {
            return this.etaWindowAfterFieldSpecified;
        }
        set {
            this.etaWindowAfterFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime stay {
        get {
            return this.stayField;
        }
        set {
            this.stayField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool staySpecified {
        get {
            return this.stayFieldSpecified;
        }
        set {
            this.stayFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal speed {
        get {
            return this.speedField;
        }
        set {
            this.speedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool speedSpecified {
        get {
            return this.speedFieldSpecified;
        }
        set {
            this.speedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal speedWindow {
        get {
            return this.speedWindowField;
        }
        set {
            this.speedWindowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool speedWindowSpecified {
        get {
            return this.speedWindowFieldSpecified;
        }
        set {
            this.speedWindowFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal windSpeed {
        get {
            return this.windSpeedField;
        }
        set {
            this.windSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool windSpeedSpecified {
        get {
            return this.windSpeedFieldSpecified;
        }
        set {
            this.windSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal windDirection {
        get {
            return this.windDirectionField;
        }
        set {
            this.windDirectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool windDirectionSpecified {
        get {
            return this.windDirectionFieldSpecified;
        }
        set {
            this.windDirectionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal currentSpeed {
        get {
            return this.currentSpeedField;
        }
        set {
            this.currentSpeedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool currentSpeedSpecified {
        get {
            return this.currentSpeedFieldSpecified;
        }
        set {
            this.currentSpeedFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal currentDirection {
        get {
            return this.currentDirectionField;
        }
        set {
            this.currentDirectionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool currentDirectionSpecified {
        get {
            return this.currentDirectionFieldSpecified;
        }
        set {
            this.currentDirectionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal windLoss {
        get {
            return this.windLossField;
        }
        set {
            this.windLossField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool windLossSpecified {
        get {
            return this.windLossFieldSpecified;
        }
        set {
            this.windLossFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal waveLoss {
        get {
            return this.waveLossField;
        }
        set {
            this.waveLossField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool waveLossSpecified {
        get {
            return this.waveLossFieldSpecified;
        }
        set {
            this.waveLossFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal totalLoss {
        get {
            return this.totalLossField;
        }
        set {
            this.totalLossField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool totalLossSpecified {
        get {
            return this.totalLossFieldSpecified;
        }
        set {
            this.totalLossFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string rpm {
        get {
            return this.rpmField;
        }
        set {
            this.rpmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string pitch {
        get {
            return this.pitchField;
        }
        set {
            this.pitchField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal fuel {
        get {
            return this.fuelField;
        }
        set {
            this.fuelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fuelSpecified {
        get {
            return this.fuelFieldSpecified;
        }
        set {
            this.fuelFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal relFuelSave {
        get {
            return this.relFuelSaveField;
        }
        set {
            this.relFuelSaveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool relFuelSaveSpecified {
        get {
            return this.relFuelSaveFieldSpecified;
        }
        set {
            this.relFuelSaveFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal absFuelSace {
        get {
            return this.absFuelSaceField;
        }
        set {
            this.absFuelSaceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool absFuelSaceSpecified {
        get {
            return this.absFuelSaceFieldSpecified;
        }
        set {
            this.absFuelSaceFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Manual {
    
    private ScheduleElement[] sheduleElementField;
    
    private Extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("sheduleElement")]
    public ScheduleElement[] sheduleElement {
        get {
            return this.sheduleElementField;
        }
        set {
            this.sheduleElementField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Schedule {
    
    private Manual manualField;
    
    private Calculated calculatedField;
    
    private Extensions extensionsField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    public Manual manual {
        get {
            return this.manualField;
        }
        set {
            this.manualField = value;
        }
    }
    
    /// <remarks/>
    public Calculated calculated {
        get {
            return this.calculatedField;
        }
        set {
            this.calculatedField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Schedules {
    
    private Schedule[] scheduleField;
    
    private Extensions extensionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("schedule")]
    public Schedule[] schedule {
        get {
            return this.scheduleField;
        }
        set {
            this.scheduleField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class GM_Point {
    
    private decimal latField;
    
    private decimal lonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal lon {
        get {
            return this.lonField;
        }
        set {
            this.lonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Waypoint {
    
    private GM_Point positionField;
    
    private Leg legField;
    
    private Extensions extensionsField;
    
    private string idField;
    
    private string revisionField;
    
    private string nameField;
    
    private decimal radiusField;
    
    private bool radiusFieldSpecified;
    
    /// <remarks/>
    public GM_Point position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public Leg leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
    public string revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusSpecified {
        get {
            return this.radiusFieldSpecified;
        }
        set {
            this.radiusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Leg {
    
    private decimal starboardXTDField;
    
    private bool starboardXTDFieldSpecified;
    
    private decimal portsideXTDField;
    
    private bool portsideXTDFieldSpecified;
    
    private decimal safetyContourField;
    
    private bool safetyContourFieldSpecified;
    
    private decimal safetyDepthField;
    
    private bool safetyDepthFieldSpecified;
    
    private GeometryType geometryTypeField;
    
    private bool geometryTypeFieldSpecified;
    
    private decimal speedMinField;
    
    private bool speedMinFieldSpecified;
    
    private decimal speedMaxField;
    
    private bool speedMaxFieldSpecified;
    
    private decimal draughtForwardField;
    
    private bool draughtForwardFieldSpecified;
    
    private decimal draughtAftField;
    
    private bool draughtAftFieldSpecified;
    
    private decimal staticUKCField;
    
    private bool staticUKCFieldSpecified;
    
    private decimal dynamicUKCField;
    
    private bool dynamicUKCFieldSpecified;
    
    private decimal mastheadField;
    
    private bool mastheadFieldSpecified;
    
    private string legReportField;
    
    private string legInfoField;
    
    private string legNote1Field;
    
    private string legNote2Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal starboardXTD {
        get {
            return this.starboardXTDField;
        }
        set {
            this.starboardXTDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool starboardXTDSpecified {
        get {
            return this.starboardXTDFieldSpecified;
        }
        set {
            this.starboardXTDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal portsideXTD {
        get {
            return this.portsideXTDField;
        }
        set {
            this.portsideXTDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool portsideXTDSpecified {
        get {
            return this.portsideXTDFieldSpecified;
        }
        set {
            this.portsideXTDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal safetyContour {
        get {
            return this.safetyContourField;
        }
        set {
            this.safetyContourField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool safetyContourSpecified {
        get {
            return this.safetyContourFieldSpecified;
        }
        set {
            this.safetyContourFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal safetyDepth {
        get {
            return this.safetyDepthField;
        }
        set {
            this.safetyDepthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool safetyDepthSpecified {
        get {
            return this.safetyDepthFieldSpecified;
        }
        set {
            this.safetyDepthFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public GeometryType geometryType {
        get {
            return this.geometryTypeField;
        }
        set {
            this.geometryTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool geometryTypeSpecified {
        get {
            return this.geometryTypeFieldSpecified;
        }
        set {
            this.geometryTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal speedMin {
        get {
            return this.speedMinField;
        }
        set {
            this.speedMinField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool speedMinSpecified {
        get {
            return this.speedMinFieldSpecified;
        }
        set {
            this.speedMinFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal speedMax {
        get {
            return this.speedMaxField;
        }
        set {
            this.speedMaxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool speedMaxSpecified {
        get {
            return this.speedMaxFieldSpecified;
        }
        set {
            this.speedMaxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal draughtForward {
        get {
            return this.draughtForwardField;
        }
        set {
            this.draughtForwardField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool draughtForwardSpecified {
        get {
            return this.draughtForwardFieldSpecified;
        }
        set {
            this.draughtForwardFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal draughtAft {
        get {
            return this.draughtAftField;
        }
        set {
            this.draughtAftField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool draughtAftSpecified {
        get {
            return this.draughtAftFieldSpecified;
        }
        set {
            this.draughtAftFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal staticUKC {
        get {
            return this.staticUKCField;
        }
        set {
            this.staticUKCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool staticUKCSpecified {
        get {
            return this.staticUKCFieldSpecified;
        }
        set {
            this.staticUKCFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal dynamicUKC {
        get {
            return this.dynamicUKCField;
        }
        set {
            this.dynamicUKCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dynamicUKCSpecified {
        get {
            return this.dynamicUKCFieldSpecified;
        }
        set {
            this.dynamicUKCFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal masthead {
        get {
            return this.mastheadField;
        }
        set {
            this.mastheadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool mastheadSpecified {
        get {
            return this.mastheadFieldSpecified;
        }
        set {
            this.mastheadFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string legReport {
        get {
            return this.legReportField;
        }
        set {
            this.legReportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string legInfo {
        get {
            return this.legInfoField;
        }
        set {
            this.legInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string legNote1 {
        get {
            return this.legNote1Field;
        }
        set {
            this.legNote1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string legNote2 {
        get {
            return this.legNote2Field;
        }
        set {
            this.legNote2Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public enum GeometryType {
    
    /// <remarks/>
    Loxodrome,
    
    /// <remarks/>
    Orthodrome,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class DefaultWaypoint {
    
    private Leg legField;
    
    private Extensions extensionsField;
    
    private decimal radiusField;
    
    private bool radiusFieldSpecified;
    
    /// <remarks/>
    public Leg leg {
        get {
            return this.legField;
        }
        set {
            this.legField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool radiusSpecified {
        get {
            return this.radiusFieldSpecified;
        }
        set {
            this.radiusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cirm.org/RTZ/1/0")]
public partial class Waypoints {
    
    private DefaultWaypoint defaultWaypointField;
    
    private Waypoint[] waypointField;
    
    private Extensions extensionsField;
    
    /// <remarks/>
    public DefaultWaypoint defaultWaypoint {
        get {
            return this.defaultWaypointField;
        }
        set {
            this.defaultWaypointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("waypoint")]
    public Waypoint[] waypoint {
        get {
            return this.waypointField;
        }
        set {
            this.waypointField = value;
        }
    }
    
    /// <remarks/>
    public Extensions extensions {
        get {
            return this.extensionsField;
        }
        set {
            this.extensionsField = value;
        }
    }
}
