///////////////////////////////////////////////////////////
//  EnumNotificationType.cs
//  Implementation of the Enumeration enumNotificationType
//  Generated by Enterprise Architect
//  Created on:      06-dec-2016 08:34:18
//  Original author: M02AMIOL
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace STM.Common.Services.Internal.Interfaces
{
    /// <summary>
    /// Types of notifications
    /// </summary>
    public enum EnumNotificationType : int
    {
        MESSAGE_WAITING = 1,
        UNAUTHORIZED_REQUEST = 2,
        ACKNOWLEDGEMENT_RECEIVED = 3,
        ERROR_MESSAGE = 4

    }//end enumNotificationType
}