//------------------------------------------------------------------------------
// <auto-generated>
//     Denna kod har genererats av ett verktyg.
//     Körtidsversion:4.0.30319.42000
//
//     Ändringar i denna fil kan orsaka fel och kommer att förloras om
//     koden återgenereras.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stmvalidation.eu/schemas/textMessageSchema_1_3.xsd")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://stmvalidation.eu/schemas/textMessageSchema_1_3.xsd", IsNullable=false)]
public partial class textMessage {
    
    private string textMessageIdField;
    
    private string informationObjectReferenceIdField;
    
    private informationObjectTypeEnum informationObjectReferenceTypeField;
    
    private bool informationObjectReferenceTypeFieldSpecified;
    
    private System.DateTime validityPeriodStartField;
    
    private bool validityPeriodStartFieldSpecified;
    
    private System.DateTime validityPeriodStopField;
    
    private bool validityPeriodStopFieldSpecified;
    
    private string authorField;
    
    private string fromField;
    
    private string serviceTypeField;
    
    private System.DateTime createdAtField;
    
    private string subjectField;
    
    private string bodyField;
    
    private GM_Point positionField;
    
    private GM_Surface areaField;
    
    /// <remarks/>
    public string textMessageId {
        get {
            return this.textMessageIdField;
        }
        set {
            this.textMessageIdField = value;
        }
    }
    
    /// <remarks/>
    public string informationObjectReferenceId {
        get {
            return this.informationObjectReferenceIdField;
        }
        set {
            this.informationObjectReferenceIdField = value;
        }
    }
    
    /// <remarks/>
    public informationObjectTypeEnum informationObjectReferenceType {
        get {
            return this.informationObjectReferenceTypeField;
        }
        set {
            this.informationObjectReferenceTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool informationObjectReferenceTypeSpecified {
        get {
            return this.informationObjectReferenceTypeFieldSpecified;
        }
        set {
            this.informationObjectReferenceTypeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime validityPeriodStart {
        get {
            return this.validityPeriodStartField;
        }
        set {
            this.validityPeriodStartField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityPeriodStartSpecified {
        get {
            return this.validityPeriodStartFieldSpecified;
        }
        set {
            this.validityPeriodStartFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime validityPeriodStop {
        get {
            return this.validityPeriodStopField;
        }
        set {
            this.validityPeriodStopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validityPeriodStopSpecified {
        get {
            return this.validityPeriodStopFieldSpecified;
        }
        set {
            this.validityPeriodStopFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    public string from {
        get {
            return this.fromField;
        }
        set {
            this.fromField = value;
        }
    }
    
    /// <remarks/>
    public string serviceType {
        get {
            return this.serviceTypeField;
        }
        set {
            this.serviceTypeField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime createdAt {
        get {
            return this.createdAtField;
        }
        set {
            this.createdAtField = value;
        }
    }
    
    /// <remarks/>
    public string subject {
        get {
            return this.subjectField;
        }
        set {
            this.subjectField = value;
        }
    }
    
    /// <remarks/>
    public string body {
        get {
            return this.bodyField;
        }
        set {
            this.bodyField = value;
        }
    }
    
    /// <remarks/>
    public GM_Point position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public GM_Surface area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stmvalidation.eu/schemas/textMessageSchema_1_3.xsd")]
public enum informationObjectTypeEnum {
    
    /// <remarks/>
    RTZ,
    
    /// <remarks/>
    S124,
    
    /// <remarks/>
    TXT,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stmvalidation.eu/schemas/textMessageSchema_1_3.xsd")]
public partial class GM_Point {
    
    private decimal latField;
    
    private decimal lonField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal lon {
        get {
            return this.lonField;
        }
        set {
            this.lonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stmvalidation.eu/schemas/textMessageSchema_1_3.xsd")]
public partial class S100_CircleByCenterPointType {
    
    private GM_Point positionField;
    
    private double radiusField;
    
    private decimal startAngleField;
    
    private decimal angularDistanceField;
    
    private string idField;
    
    public S100_CircleByCenterPointType() {
        this.startAngleField = ((decimal)(0.0m));
        this.angularDistanceField = ((decimal)(360.0m));
    }
    
    /// <remarks/>
    public GM_Point position {
        get {
            return this.positionField;
        }
        set {
            this.positionField = value;
        }
    }
    
    /// <remarks/>
    public double radius {
        get {
            return this.radiusField;
        }
        set {
            this.radiusField = value;
        }
    }
    
    /// <remarks/>
    public decimal startAngle {
        get {
            return this.startAngleField;
        }
        set {
            this.startAngleField = value;
        }
    }
    
    /// <remarks/>
    public decimal angularDistance {
        get {
            return this.angularDistanceField;
        }
        set {
            this.angularDistanceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://stmvalidation.eu/schemas/textMessageSchema_1_3.xsd")]
public partial class GM_Surface {
    
    private GM_SurfacePolygon polygonField;
    
    private S100_CircleByCenterPointType circleField;
    
    /// <remarks/>
    public GM_SurfacePolygon Polygon {
        get {
            return this.polygonField;
        }
        set {
            this.polygonField = value;
        }
    }
    
    /// <remarks/>
    public S100_CircleByCenterPointType Circle {
        get {
            return this.circleField;
        }
        set {
            this.circleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://stmvalidation.eu/schemas/textMessageSchema_1_3.xsd")]
public partial class GM_SurfacePolygon {
    
    private string posListField;
    
    private string idField;
    
    private uint countField;
    
    private bool countFieldSpecified;
    
    private ushort srsDimensionField;
    
    private bool srsDimensionFieldSpecified;
    
    private string srsNameField;
    
    /// <remarks/>
    public string posList {
        get {
            return this.posListField;
        }
        set {
            this.posListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public uint count {
        get {
            return this.countField;
        }
        set {
            this.countField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool countSpecified {
        get {
            return this.countFieldSpecified;
        }
        set {
            this.countFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ushort srsDimension {
        get {
            return this.srsDimensionField;
        }
        set {
            this.srsDimensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool srsDimensionSpecified {
        get {
            return this.srsDimensionFieldSpecified;
        }
        set {
            this.srsDimensionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string srsName {
        get {
            return this.srsNameField;
        }
        set {
            this.srsNameField = value;
        }
    }
}
