/*
 * STM Voyage Information Service SeaSWIM API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class DeliveryAck :  IEquatable<DeliveryAck>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeliveryAck" /> class.
        /// </summary>
        /// <param name="Id">Id.</param>
        /// <param name="ReferenceId">ReferenceId.</param>
        /// <param name="TimeOfDelivery">TimeOfDelivery.</param>
        /// <param name="FromId">FromId.</param>
        /// <param name="FromName">FromName.</param>
        /// <param name="ToId">ToId.</param>
        /// <param name="ToName">ToName.</param>
        /// <param name="AckResult">AckResult.</param>
        public DeliveryAck(string Id = null, string ReferenceId = null, DateTime? TimeOfDelivery = null, string FromId = null, string FromName = null, string ToId = null, string ToName = null, string AckResult = null)
        {
            this.Id = Id;
            this.ReferenceId = ReferenceId;
            this.TimeOfDelivery = TimeOfDelivery;
            this.FromId = FromId;
            this.FromName = FromName;
            this.ToId = ToId;
            this.ToName = ToName;
            this.AckResult = AckResult;
            
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets ReferenceId
        /// </summary>
        [DataMember(Name="referenceId")]
        public string ReferenceId { get; set; }

        /// <summary>
        /// Gets or Sets TimeOfDelivery
        /// </summary>
        [DataMember(Name="timeOfDelivery")]
        public DateTime? TimeOfDelivery { get; set; }

        /// <summary>
        /// Gets or Sets FromId
        /// </summary>
        [DataMember(Name="fromId")]
        public string FromId { get; set; }

        /// <summary>
        /// Gets or Sets FromName
        /// </summary>
        [DataMember(Name="fromName")]
        public string FromName { get; set; }

        /// <summary>
        /// Gets or Sets ToId
        /// </summary>
        [DataMember(Name="toId")]
        public string ToId { get; set; }

        /// <summary>
        /// Gets or Sets ToName
        /// </summary>
        [DataMember(Name="toName")]
        public string ToName { get; set; }

        /// <summary>
        /// Gets or Sets AckResult
        /// </summary>
        [DataMember(Name="ackResult")]
        public string AckResult { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeliveryAck {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ReferenceId: ").Append(ReferenceId).Append("\n");
            sb.Append("  TimeOfDelivery: ").Append(TimeOfDelivery).Append("\n");
            sb.Append("  FromId: ").Append(FromId).Append("\n");
            sb.Append("  FromName: ").Append(FromName).Append("\n");
            sb.Append("  ToId: ").Append(ToId).Append("\n");
            sb.Append("  ToName: ").Append(ToName).Append("\n");
            sb.Append("  AckResult: ").Append(AckResult).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((DeliveryAck)obj);
        }

        /// <summary>
        /// Returns true if DeliveryAck instances are equal
        /// </summary>
        /// <param name="other">Instance of DeliveryAck to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeliveryAck other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.ReferenceId == other.ReferenceId ||
                    this.ReferenceId != null &&
                    this.ReferenceId.Equals(other.ReferenceId)
                ) && 
                (
                    this.TimeOfDelivery == other.TimeOfDelivery ||
                    this.TimeOfDelivery != null &&
                    this.TimeOfDelivery.Equals(other.TimeOfDelivery)
                ) && 
                (
                    this.FromId == other.FromId ||
                    this.FromId != null &&
                    this.FromId.Equals(other.FromId)
                ) && 
                (
                    this.FromName == other.FromName ||
                    this.FromName != null &&
                    this.FromName.Equals(other.FromName)
                ) && 
                (
                    this.ToId == other.ToId ||
                    this.ToId != null &&
                    this.ToId.Equals(other.ToId)
                ) && 
                (
                    this.ToName == other.ToName ||
                    this.ToName != null &&
                    this.ToName.Equals(other.ToName)
                ) && 
                (
                    this.AckResult == other.AckResult ||
                    this.AckResult != null &&
                    this.AckResult.Equals(other.AckResult)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                    if (this.ReferenceId != null)
                    hash = hash * 59 + this.ReferenceId.GetHashCode();
                    if (this.TimeOfDelivery != null)
                    hash = hash * 59 + this.TimeOfDelivery.GetHashCode();
                    if (this.FromId != null)
                    hash = hash * 59 + this.FromId.GetHashCode();
                    if (this.FromName != null)
                    hash = hash * 59 + this.FromName.GetHashCode();
                    if (this.ToId != null)
                    hash = hash * 59 + this.ToId.GetHashCode();
                    if (this.ToName != null)
                    hash = hash * 59 + this.ToName.GetHashCode();
                    if (this.AckResult != null)
                    hash = hash * 59 + this.AckResult.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(DeliveryAck left, DeliveryAck right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DeliveryAck left, DeliveryAck right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
