/*
 * STM Voyage Information Service SeaSWIM API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace STM.VIS.Services.Private.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class GetVPResponseObject :  IEquatable<GetVPResponseObject>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetVPResponseObject" /> class.
        /// </summary>
        /// <param name="LastInteractionTime">Gets or Sets LastInteractionTime.</param>
        /// <param name="VoyagePlan">Gets or Sets VoyagePlan.</param>
        public GetVPResponseObject(DateTime? LastInteractionTime = null, List<VoyagePlan> VoyagePlan = null)
        {
            this.LastInteractionTime = LastInteractionTime;
            this.VoyagePlan = VoyagePlan;
            
        }

        /// <summary>
        /// Gets or Sets LastInteractionTime
        /// </summary>
        /// <value>Gets or Sets LastInteractionTime</value>
        [DataMember(Name="lastInteractionTime")]
        public DateTime? LastInteractionTime { get; set; }

        /// <summary>
        /// Gets or Sets VoyagePlan
        /// </summary>
        /// <value>Gets or Sets VoyagePlan</value>
        [DataMember(Name="voyagePlan")]
        public List<VoyagePlan> VoyagePlan { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetVPResponseObject {\n");
            sb.Append("  LastInteractionTime: ").Append(LastInteractionTime).Append("\n");
            sb.Append("  VoyagePlan: ").Append(VoyagePlan).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((GetVPResponseObject)obj);
        }

        /// <summary>
        /// Returns true if GetVPResponseObject instances are equal
        /// </summary>
        /// <param name="other">Instance of GetVPResponseObject to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetVPResponseObject other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.LastInteractionTime == other.LastInteractionTime ||
                    this.LastInteractionTime != null &&
                    this.LastInteractionTime.Equals(other.LastInteractionTime)
                ) && 
                (
                    this.VoyagePlan == other.VoyagePlan ||
                    this.VoyagePlan != null &&
                    this.VoyagePlan.SequenceEqual(other.VoyagePlan)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.LastInteractionTime != null)
                    hash = hash * 59 + this.LastInteractionTime.GetHashCode();
                    if (this.VoyagePlan != null)
                    hash = hash * 59 + this.VoyagePlan.GetHashCode();
                return hash;
            }
        }

        #region Operators

        /// <summary>
        /// 
        /// </summary>
        /// <param name="left"></param>
        /// <param name="right"></param>
        /// <returns></returns>
        public static bool operator ==(GetVPResponseObject left, GetVPResponseObject right)
        {
            return Equals(left, right);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="left"></param>
        /// <param name="right"></param>
        /// <returns></returns>
        public static bool operator !=(GetVPResponseObject left, GetVPResponseObject right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
