///////////////////////////////////////////////////////////
//  ConnectionStatus.cs
//  Implementation of the Enumeration ConnectionStatus
//  Generated by Enterprise Architect
//  Created on:      18-nov-2016 13:07:44
//  Original author: M02AMIOL
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace STM.Common.DataAccess.Entities
{

    public enum ConnectionStatus : int
    {

        unknown = -1,
        unconnected = 0,
        connected = 1

    }//end ConnectionStatus
}