///////////////////////////////////////////////////////////
//  EventNumber.cs
//  Implementation of the Enumeration EventNumber
//  Generated by Enterprise Architect
//  Created on:      18-nov-2016 13:07:18
//  Original author: M02AMIOL
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace STM.Common.DataAccess.Entities
{

    	/// <summary>
	/// Enumeration with event numbers
	/// </summary>
    public enum EventNumber : int
    {
        VIS_getVoyagePlan_request = 1,
        VIS_getVoyagePlan_response = 2,
        VIS_uploadVoyagePlan_request = 3,
        VIS_uploadVoyagePlan_response = 4,
        VIS_uploadTextMessage_request = 5,
        VIS_uploadTextMessage_response = 6,
        VIS_uploadAreaMessage_request = 7,
        VIS_uploadAreaMessage_response = 8,
        VIS_subscribeToVoyagePlan_request = 9,
        VIS_subscribeToVoyagePlan_response = 10,
        VIS_removeSubscribeToVoyagePlan_request = 11,
        VIS_removeSubscribeToVoyagePlan_response = 12,
        VIS_acknowledgement_request = 13,
        VIS_acknowledgement_response = 14,
        VIS_publishMessage = 15,
        VIS_sendAcknowledgement = 16,
        VIS_consumeService = 17,
        SPIS_amss_request = 18,
        SPIS_amss_response = 19,
        SPIS_stateUpdate_request = 20,
        SPIS_stateUpdate_response = 21,
        SPIS_consumeService = 22,
        SPIS_uploadTextMessage_request = 23,
        SPIS_uploadTextMessage_response = 24,
        SPIS_uploadAreaMessage_request = 25,
        SPIS_uploadAreaMessage_response = 26,
        SPIS_uploadPCM_response = 27,
        SPIS_uploadPCM_request = 28,
        VIS_checkSubscribeToVoyagePlan_request = 29,
        VIS_checkSubscribeToVoyagePlan_response = 30


    }//end EventNumber
}