///////////////////////////////////////////////////////////
//  Identity.cs
//  Implementation of the Class Identity
//  Generated by Enterprise Architect
//  Created on:      18-nov-2016 13:07:32
//  Original author: M02AMIOL
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ComponentModel.DataAnnotations;

namespace STM.Common.DataAccess.Entities
{

    public class Identity
    {

        /// <summary>
        /// Unique internal ID
        /// </summary>
        public long ID { get; set; }

        /// <summary>
        /// Name of identity (ISSUE Could be that we need to store more information from
        /// the certificate (or store the certificate)
        /// </summary>
        public string Name { get; set; }

        [Required]
        public string UID { get; set; }
    }//end Identity
}