///////////////////////////////////////////////////////////
//  MessageType.cs
//  Implementation of the Class MessageType
//  Generated by Enterprise Architect
//  Created on:      18-nov-2016 13:06:44
//  Original author: M02AMIOL
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;


namespace STM.Common.DataAccess.Entities
{

    	/// <summary>
	/// Type of messages
	/// </summary>
    public class MessageType
    {

        /// <summary>
        /// Port Call Message in XML
        /// </summary>
        public long ID { get; set; }

        /// <summary>
        /// Name of message type
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Schema XSD
        /// </summary>
        public string SchemaXSD { get; set; }


    }//end MessageType
}