/*
 * STM Voyage Information Service STM Onboard API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using STM.StmModule.Simulator.Contract;

namespace STM.StmModule.Simulator.Contract
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ServiceInstance :  IEquatable<ServiceInstance>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ServiceInstance" /> class.
        /// </summary>
        /// <param name="Comment">Comment.</param>
        /// <param name="EndpointType">EndpointType.</param>
        /// <param name="EndpointUri">EndpointUri.</param>
        /// <param name="InstanceAsXml">InstanceAsXml.</param>
        /// <param name="InstanceId">InstanceId.</param>
        /// <param name="Keywords">Keywords.</param>
        /// <param name="Name">Name.</param>
        /// <param name="OrganizationId">OrganizationId.</param>
        /// <param name="Status">Status.</param>
        /// <param name="Unlocode">Unlocode.</param>
        /// <param name="Version">Version.</param>
        public ServiceInstance(string Comment = null, string EndpointType = null, string EndpointUri = null, Xml InstanceAsXml = null, string InstanceId = null, string Keywords = null, string Name = null, string OrganizationId = null, string Status = null, string Unlocode = null, string Version = null)
        {
            this.Comment = Comment;
            this.EndpointType = EndpointType;
            this.EndpointUri = EndpointUri;
            this.InstanceAsXml = InstanceAsXml;
            this.InstanceId = InstanceId;
            this.Keywords = Keywords;
            this.Name = Name;
            this.OrganizationId = OrganizationId;
            this.Status = Status;
            this.Unlocode = Unlocode;
            this.Version = Version;
            
        }

        /// <summary>
        /// Gets or Sets Comment
        /// </summary>
        [DataMember(Name="comment")]
        public string Comment { get; set; }

        /// <summary>
        /// Gets or Sets EndpointType
        /// </summary>
        [DataMember(Name="endpointType")]
        public string EndpointType { get; set; }

        /// <summary>
        /// Gets or Sets EndpointUri
        /// </summary>
        [DataMember(Name="endpointUri")]
        public string EndpointUri { get; set; }

        /// <summary>
        /// Gets or Sets InstanceAsXml
        /// </summary>
        [DataMember(Name="instanceAsXml")]
        public Xml InstanceAsXml { get; set; }

        /// <summary>
        /// Gets or Sets InstanceId
        /// </summary>
        [DataMember(Name="instanceId")]
        public string InstanceId { get; set; }

        /// <summary>
        /// Gets or Sets Keywords
        /// </summary>
        [DataMember(Name="keywords")]
        public string Keywords { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [DataMember(Name="organizationId")]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name="status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Unlocode
        /// </summary>
        [DataMember(Name="unlocode")]
        public string Unlocode { get; set; }

        /// <summary>
        /// Gets or Sets Version
        /// </summary>
        [DataMember(Name="version")]
        public string Version { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ServiceInstance {\n");
            sb.Append("  Comment: ").Append(Comment).Append("\n");
            sb.Append("  EndpointType: ").Append(EndpointType).Append("\n");
            sb.Append("  EndpointUri: ").Append(EndpointUri).Append("\n");
            sb.Append("  InstanceAsXml: ").Append(InstanceAsXml).Append("\n");
            sb.Append("  InstanceId: ").Append(InstanceId).Append("\n");
            sb.Append("  Keywords: ").Append(Keywords).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Unlocode: ").Append(Unlocode).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            if (obj.GetType() != GetType()) return false;
            return Equals((ServiceInstance)obj);
        }

        /// <summary>
        /// Returns true if ServiceInstance instances are equal
        /// </summary>
        /// <param name="other">Instance of ServiceInstance to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ServiceInstance other)
        {

            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    this.Comment == other.Comment ||
                    this.Comment != null &&
                    this.Comment.Equals(other.Comment)
                ) && 
                (
                    this.EndpointType == other.EndpointType ||
                    this.EndpointType != null &&
                    this.EndpointType.Equals(other.EndpointType)
                ) && 
                (
                    this.EndpointUri == other.EndpointUri ||
                    this.EndpointUri != null &&
                    this.EndpointUri.Equals(other.EndpointUri)
                ) && 
                (
                    this.InstanceAsXml == other.InstanceAsXml ||
                    this.InstanceAsXml != null &&
                    this.InstanceAsXml.Equals(other.InstanceAsXml)
                ) && 
                (
                    this.InstanceId == other.InstanceId ||
                    this.InstanceId != null &&
                    this.InstanceId.Equals(other.InstanceId)
                ) && 
                (
                    this.Keywords == other.Keywords ||
                    this.Keywords != null &&
                    this.Keywords.Equals(other.Keywords)
                ) && 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.OrganizationId == other.OrganizationId ||
                    this.OrganizationId != null &&
                    this.OrganizationId.Equals(other.OrganizationId)
                ) && 
                (
                    this.Status == other.Status ||
                    this.Status != null &&
                    this.Status.Equals(other.Status)
                ) && 
                (
                    this.Unlocode == other.Unlocode ||
                    this.Unlocode != null &&
                    this.Unlocode.Equals(other.Unlocode)
                ) && 
                (
                    this.Version == other.Version ||
                    this.Version != null &&
                    this.Version.Equals(other.Version)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                    if (this.Comment != null)
                    hash = hash * 59 + this.Comment.GetHashCode();
                    if (this.EndpointType != null)
                    hash = hash * 59 + this.EndpointType.GetHashCode();
                    if (this.EndpointUri != null)
                    hash = hash * 59 + this.EndpointUri.GetHashCode();
                    if (this.InstanceAsXml != null)
                    hash = hash * 59 + this.InstanceAsXml.GetHashCode();
                    if (this.InstanceId != null)
                    hash = hash * 59 + this.InstanceId.GetHashCode();
                    if (this.Keywords != null)
                    hash = hash * 59 + this.Keywords.GetHashCode();
                    if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                    if (this.OrganizationId != null)
                    hash = hash * 59 + this.OrganizationId.GetHashCode();
                    if (this.Status != null)
                    hash = hash * 59 + this.Status.GetHashCode();
                    if (this.Unlocode != null)
                    hash = hash * 59 + this.Unlocode.GetHashCode();
                    if (this.Version != null)
                    hash = hash * 59 + this.Version.GetHashCode();
                return hash;
            }
        }

        #region Operators

        public static bool operator ==(ServiceInstance left, ServiceInstance right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ServiceInstance left, ServiceInstance right)
        {
            return !Equals(left, right);
        }

        #endregion Operators

    }
}
